[package]
name = "anticaps_fgen"
version = "0.1.0"
authors = ["rph <rphsoftware@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minidom = "0.12.0"